### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by AY1997** [liuyuan-pal/NeRO#1]
Hi, thank you for your impressive work!
If I have a set of 360 inward images, how to make a dataset like GlossyReal? Specifically, how do I get the ply file of the point cloud, can I convert it directly through the points3D.bin file of colmap?

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest in our work! We will release instructions about how to reconstruct a custom object in two weeks. Thanks for your understanding!

**Comment by liuyuan-pal** [comment]
Hi, I've updated the instructions to train custom objects. Thanks for waiting!

**Comment by AY1997** [comment]
> Hi, I've updated the instructions to train custom objects. Thanks for waiting!

Got it! Thanks again.
