### ISSUE TITLE
xyz direction for kettle demo in CloudCompare

### ISSUE THREAD

**Issue by monajalal** [liuyuan-pal/NeRO#14]
I have this:
![Screenshot from 2023-06-20 14-02-54](https://github.com/liuyuan-pal/NeRO/assets/1892917/8c52faa4-bf33-4e30-99d2-506239bbf232)

and you have:
![Screenshot from 2023-06-20 14-03-03](https://github.com/liuyuan-pal/NeRO/assets/1892917/6d2aac4f-4f69-4d58-ac6e-7a765b6e56ba)

does it mean my xyz direction is wrong? Could you give some tips how you want it to be fixed? I am looking at the lower right corner.

**Comment by liuyuan-pal** [comment]
Your X+ direction is also right, the x+ direction can be arbitrary on the plane of the board.
