### ISSUE TITLE
NeRF_blender datasets

### ISSUE THREAD

**Issue by Riga27527** [liuyuan-pal/NeRO#17]
Thank you for your impressive work!
Have you tested under NeRF's synthetic dataset? For example the ShinyBlender dataset from Ref-NeRF.
By the way, I'm still curious about how your work performs under diffuse-like objects? Any clues would be greatly appreciated!

**Comment by liuyuan-pal** [comment]
Hi, I don't test it on the NeRF synthetic dataset but I have tried it on the ShinyBlender dataset. It is able to work quite well on watertight objects, no matter whether they are diffuse-like or reflective, but has difficulty handling non-watertight objects because NeRO is based on SDF and SDF will struggle to reconstruct objects without closed shapes. As you can see, it is able to recostruct the non-reflective surfaces and their BRDF like the board in the `kettle` example in https://github.com/liuyuan-pal/NeRO/blob/main/assets/custom-result.png.

![image](https://github.com/liuyuan-pal/NeRO/assets/23974453/de6a49cb-2811-4b6e-8eeb-8d186d4c1b31)
![image](https://github.com/liuyuan-pal/NeRO/assets/23974453/fde2b8f5-3a39-4257-b77c-06dba26ce331)

**Comment by Riga27527** [comment]
> Hi, I don't test it on the NeRF synthetic dataset but I have tried it on the ShinyBlender dataset. It is able to work quite well on watertight objects, no matter whether they are diffuse-like or reflective, but has difficulty handling non-watertight objects because NeRO is based on SDF and SDF will struggle to reconstruct objects without closed shapes. As you can see, it is able to recostruct the non-reflective surfaces and their BRDF like the board in the `kettle` example in https://github.com/liuyuan-pal/NeRO/blob/main/assets/custom-result.png.
> 
> ![image](https://user-images.githubusercontent.com/23974453/251625087-de6a49cb-2811-4b6e-8eeb-8d186d4c1b31.png) ![image](https://user-images.githubusercontent.com/23974453/251625094-fde2b8f5-3a39-4257-b77c-06dba26ce331.png)

Thank you for your wonderful reply! I still have some small implementation problems. Since NeRF_blender's near and far are 2 and 6 respectively, how much do i need to adjust the 'self.scale_factor' to load these datasets? In addition, should the judgment of 'inner_mask' be changed in functions such as 'compute_occ_loss' ?

**Comment by liuyuan-pal** [comment]
Hi, we only need to ensure the object is inside the sphere of 1 radius on the origin. For the shiny blender dataset, I use a scale factor of 0.7 for the helmet and the toaster. You may determine this factor using the rendered depth maps.

**Comment by xdobetter** [comment]
Thanks for your great work. Could you give me some pieces of advice on how to  train in custom synthetic data (i.e., nerf synthetic data or ShinyBlender dataset)

**Comment by Riga27527** [comment]
> Thanks for your great work. Could you give me some pieces of advice on how to train in custom synthetic data (i.e., nerf synthetic data or ShinyBlender dataset)

You only need to replace the corresponding camera intrinsic matrix ( i.e., function get_K) and pose matrix (i.e., function get_pose) with the parameters of the NeRF synthetic data set (you can refer to NeRF's codes), and adjust the scale_factor (such as 0.5) to make the scene within the unit sphere.

**Comment by g3956** [comment]
H

> 

Hi Team, 

Thanks for sharing the wonderful work and amazing codebase! I tried to load the ShinyBlneder dataset from NeRF's codes by replacing the corresponding camera intrinsic matrix and camera pose and adjusting the scale_factor to 0.5 to make sure the object within the unit sphere, but the result is like this:

<img width="626" alt="image" src="https://github.com/liuyuan-pal/NeRO/assets/48900732/b7b318b6-74f3-491a-bf43-135f78785738">

It seems that the pose is not correct.  Appreciate very much for any comment! 

Thanks

**Comment by liuyuan-pal** [comment]
Hi, we adopt the world-to-camera pose here. 
`pose=[R;t]` and `x_cam = R @ x_world + t`.
Note the pose inverse means we transfer the provided camera-to-world pose to the world-to-camera pose.

![image](https://github.com/liuyuan-pal/NeRO/assets/23974453/a00b4472-c2da-4b86-a203-f39511d5922f)

**Comment by g3956** [comment]
Thanks for your help. It works now.

**Comment by cmh1027** [comment]
@liuyuan-pal Do camera data in Glossy dataset contain w2c matrix, or c2w matrix? I'm struggling with reformatting glossy dataset into blender-like format
