### ISSUE TITLE
Bad results on non-reflective objects

### ISSUE THREAD

**Issue by yankeesong** [liuyuan-pal/NeRO#22]
Solved.

**Comment by liuyuan-pal** [comment]
Hi! Do the early stage results (like on step 1k or 5k or less) also look like this? It seems that the foreground SDF does not contain any surfaces.

**Comment by yankeesong** [comment]
![4999-index-0](https://github.com/liuyuan-pal/NeRO/assets/36912641/c81b373c-ad8d-4526-916b-aec7d614bd83)

This is step 5000 (it seems the default config doesn't save for less than 5000). Are there any suggestions to improve the quality?

**Comment by liuyuan-pal** [comment]
Maybe you need to specify the `object_point_cloud.ply` a little bit smaller, because it is supposed to include the object but not too larger than the object.
