### ISSUE TITLE
Extracting light from the BRDF estimation

### ISSUE THREAD

**Issue by adli-igc** [liuyuan-pal/NeRO#24]
How do you extract the light as shown in Figure 18 in the published paper?

**Comment by liuyuan-pal** [comment]
Hi, you may load the checkpoint and specify the query light direction here 
https://github.com/liuyuan-pal/NeRO/blob/3b4d421a646097e7d59557c5ea24f4281ab38ef1/network/field.py#L564
Note you need to do gamma correction before outputting the lights as an image.

**Comment by adli-igc** [comment]
Thanks

**Comment by prakashknaikade** [comment]
hello,
can you please share the code for it and how to do it?
@adli-igc

**Comment by prakashknaikade** [comment]
@adli-igc Could you please share the code to do this?

**Comment by adli-igc** [comment]
Hi @prakashknaikade , sorry but I did not implement it in the code. It was question that popped up as I was reading the paper
