### ISSUE TITLE
Render video with custom camera path, mapping extracted matrial to different mesh 

### ISSUE THREAD

**Issue by prakashknaikade** [liuyuan-pal/NeRO#27]
Thanks for great work.
1. How we can render video with custom camera path like nerfstudio with original/other lighting envs?
2. How the relighting video shown on project page is rendered?
3.  How to map extracted material to different object's mesh?

**Comment by liuyuan-pal** [comment]
Hi, thanks for trying our codes.
1. The current codes does not support arbitrary camera paths. You may need to implement it yourself.
For 2.  and 3., you may refer to the rendering scripts of relighting.

**Comment by prakashknaikade** [comment]
Hi, thanks for the reply.
From where we can access extracted lighting env to use it in rendering scripts of relighting?

**Comment by liuyuan-pal** [comment]
Hi, the released codes do not provide interfaces to extract lighting env. You may need to refer https://github.com/liuyuan-pal/NeRO/blob/3b4d421a646097e7d59557c5ea24f4281ab38ef1/network/field.py#L564
to extract the env lights and save it as an .exr file.

**Comment by prakashknaikade** [comment]
Hi, thanks for the reply.
@liuyuan-pal Can you please elaborate little more about the solution you provided?
