### ISSUE TITLE
Size of ArUco board

### ISSUE THREAD

**Issue by zhangwenniu** [liuyuan-pal/NeRO#28]
Thanks for your excellent job, the results are amazing! 
Since I want to create my own dataset, I would like to know the **size of your aruco board**, as well as the **material of aruco board**. For example, 50 cm x 50 cm or 80 cm x 80 cm? For the material of aruco board: is it a plastic board with a printed color paper on it, or the hard foam board? 
Thanks for your help!

**Comment by liuyuan-pal** [comment]
Hi, it's 50cm*50cm. It's plastics with patterns printed on it. You may buy it on taobao.

**Comment by zhangwenniu** [comment]
Thanks for your kind reply! Really helps!
