### ISSUE TITLE
Test images for novel view synthesis

### ISSUE THREAD

**Issue by sjj118** [liuyuan-pal/NeRO#32]
Thank you for your excellent work!

In appendix of the paper, you mentioned that 8 additional test images were rendered to evaluate the NVS quality, but I could not find these test images in the Glossy-Blender dataset.

Can you share the test images for novel view synthesis to me?

Thanks!

**Comment by liuyuan-pal** [comment]
Thanks! I've just uploaded it here.
https://connecthkuhk-my.sharepoint.com/:u:/g/personal/yuanly_connect_hku_hk/Ec1RO-NIV_BJjLpPZyb-Um8BVW4g7BaE_JZrqeUcYEF2_w?e=fR3SO6
