### ISSUE TITLE
material estimation problem 

### ISSUE THREAD

**Issue by wooni-github** [liuyuan-pal/NeRO#35]
Hi, I encountered a problem while estimating materials using my own data. 

The shape reconstruction was successful, producing a reliable .ply file with a size similar to other pre-trained meshes. 

However, when I attempted material estimation, it resulted in all black images saved at data/train_vis/own_data/*.jpg. 
(I successfully performed material estimation on the given datasets using NeRO)

Additionally, a warning message appeared: 

```warning!!! The max_distance from the camera is 12.2236, which exceeds the 10.0 limit for the ray tracer.```

also ```NaN or Inf found in input tensor.```. 

 I used the same parameters for material estimation in the yaml file. How can I correct this issue?

**Comment by liuyuan-pal** [comment]
Hi, you may scale down the whole scene to make sure the camera is not too far away (less than 10) from the object in stage II. This seems to be a problem in the `RayTracer`.
