### ISSUE TITLE
G.T. glossy real mask

### ISSUE THREAD

**Issue by ccetaw** [liuyuan-pal/NeRO#46]
Hi! 
Thank you for your marvellous work! I am trying to run previous methods like NDR and NDRMC on glossy real dataset, but the ground truth mask is missing. Could you please share the G.T. mask for glossy real dataset?

Thank you very much in advcance!

**Comment by liuyuan-pal** [comment]
Hi, you may reproject the GT model onto images to get the masks for training NDR and NDRMC, which is how I implement for these two baselines.
