### ISSUE TITLE
inference on custom data or any test data

### ISSUE THREAD

**Issue by monajalal** [liuyuan-pal/NeRO#8]
could you please provide share the code for getting inference on a set of images taken by multiple cameras from a single object?
do I need to have access to camera calibration information in order to use your code?

Let's say I have 5 cameras and each taken 24 images of a custom object and the cameras change position and rotate. However, I don't have access to camera calibration matrix info (K).

**Comment by liuyuan-pal** [comment]
Hi, you may just disable the `--same_camera`. Without such a parameter, COLMAP will use different camera models for different images. The intrinsics are all resolved by the COLMAP and I just initialize the focal length with `sqrt(h**2+w**2)`. You may refer to the documents of COLMAP to carefully tune the camera intrinsics.
